apiVersion: v1
data:
  config.yaml: |
    domain: global-ratelimit
    descriptors:
      - key: PARTNER
        value: CUSTOMER_ID_1
        descriptors:
        - key: PATH
          value: /api_v3/service/configurations/action/servebydevice
          rate_limit:
            unit: minute
            requests_per_unit: 5000
        - key: PATH
          value: /api_v3/service/ENDPOINT_8playbackcontext
          rate_limit:
            unit: minute
            requests_per_unit: 45000
        - key: PATH
          value: /api_v3/service/userassetrule/action/list
          rate_limit:
            unit: minute
            requests_per_unit: 58000
        - key: PATH
          value: /api_v3/service/licensedurl/action/get
          rate_limit:
            unit: minute
            requests_per_unit: 58000
        - key: PATH
          value: /api_v3/service/assethistory/action/list
          rate_limit:
            unit: minute
            requests_per_unit: 35000
      - key: PARTNER
        value: CUSTOMER_ID_3
        descriptors:
        - key: PATH
          value: /api_v3/service/ENDPOINT_5
          rate_limit:
            unit: minute
            requests_per_unit: 12000
        - key: PATH
          value: /api_v3/service/userassetrule/action/list
          rate_limit:
            unit: minute
            requests_per_unit: 58000
        - key: PATH
          value: /api_v3/service/ENDPOINT_2
          rate_limit:
            unit: minute
            requests_per_unit: 70000
        - key: PATH
          value: /api_v3/service/assethistory/action/list
          rate_limit:
            unit: minute
            requests_per_unit: 35000
      - key: PARTNER
        value: CUSTOMER_ID_4
        descriptors:
        - key: PATH
          value: /api_v3/service/ENDPOINT_7
          rate_limit:
            unit: minute
            requests_per_unit: 35000
        - key: PATH
          value: /api_v3/service/householdquota/action/get
          rate_limit:
            unit: minute
            requests_per_unit: 35000
        - key: PATH
          value: /api_v3/service/ENDPOINT_2
          rate_limit:
            unit: minute
            requests_per_unit: 35000
        - key: PATH
          value: /api_v3/service/configurations/action/servebydevice
          rate_limit:
            unit: minute
            requests_per_unit: 500
      - key: PARTNER
        value: CUSTOMER_ID_2
        descriptors:
        - key: PATH
          value: /api_v3/service/assethistory/action/list
          rate_limit:
            unit: minute
            requests_per_unit: 35000
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: orp2-istio-ratelimit
  name: ratelimit-config
  namespace: istio-system