apiVersion: batch/v1
kind: Job
metadata:
  name: adaptive-rate-limiter-job
  namespace: istio-system
  labels:
    app: adaptive-rate-limiter
    component: job
spec:
  template:
    metadata:
      labels:
        app: adaptive-rate-limiter
        component: job
    spec:
      serviceAccountName: adaptive-rate-limiter
      containers:
      - name: adaptive-rate-limiter
        image: litanshamir/ratelimit_values:latest
        command: ["python3", "scripts/main.py"]
        env:
        - name: CONFIG_PATH
          value: "/etc/config/config.yaml"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: kubeconfig-volume
          mountPath: /root/.kube
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: config-volume
        configMap:
          name: rate-limit-values-config
      - name: kubeconfig-volume
        secret:
          secretName: kubeconfig-secret
          optional: true
      restartPolicy: Never
  backoffLimit: 3
  activeDeadlineSeconds: 1800  # 30 minutes timeout