apiVersion: batch/v1
kind: CronJob
metadata:
  name: adaptive-rate-limiter-cronjob
  namespace: istio-system
  labels:
    app: adaptive-rate-limiter
    component: cronjob
spec:
  schedule: "0 */6 * * *"  # Run every 6 hours
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: adaptive-rate-limiter
            component: cronjob
        spec:
          serviceAccountName: adaptive-rate-limiter
          containers:
          - name: adaptive-rate-limiter
            image: litanshamir/ratelimit_values:latest
            command: ["python3", "scripts/main.py"]
            env:
            - name: CONFIG_PATH
              value: "/etc/config/config.yaml"
            volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: kubeconfig-volume
              mountPath: /root/.kube
              readOnly: true
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          volumes:
          - name: config-volume
            configMap:
              name: rate-limit-values-config
          - name: kubeconfig-volume
            secret:
              secretName: kubeconfig-secret
              optional: true
          restartPolicy: OnFailure
      backoffLimit: 2
      activeDeadlineSeconds: 1800  # 30 minutes timeout
