apiVersion: v1
kind: ServiceAccount
metadata:
  name: adaptive-rate-limiter
  namespace: istio-system
  labels:
    app: adaptive-rate-limiter
    component: service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: adaptive-rate-limiter
  labels:
    app: adaptive-rate-limiter
    component: rbac
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: adaptive-rate-limiter
  labels:
    app: adaptive-rate-limiter
    component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: adaptive-rate-limiter
subjects:
- kind: ServiceAccount
  name: adaptive-rate-limiter
  namespace: istio-system