apiVersion: batch/v1
kind: Job
metadata:
  name: rate-limit-job
  namespace: istio-system
spec:
  template:
    metadata:
      labels:
        app: rate-limit-app
    spec:
      containers:
      - name: rate-limit-container
        image: litanshamir/ratelimit_values:latest
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config/config.yaml
          subPath: config.yaml
        - name: ratelimit-config-volume
          mountPath: /etc/config/ratelimit-config.yaml
          subPath: config.yaml
      volumes:
      - name: config-volume
        configMap:
          name: rate-limit-values-config
          items:
          - key: config.yaml
            path: config.yaml
      - name: ratelimit-config-volume
        configMap:
          name: ratelimit-config
          items:
          - key: config.yaml
            path: config.yaml
      restartPolicy: Never
