apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-limit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rate-limit-app
  template:
    metadata:
      labels:
        app: rate-limit-app
    spec:
      containers:
      - name: rate-limit-container
        image: litanshamir/ratelimit_values:latest
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config/config.yaml
          subPath: config.yaml
      volumes:
      - name: config-volume
        configMap:
          name: rate-limit-values-config
          items:
          - key: config.yaml
            path: config.yaml
