# Local Development Environment Configuration
# This file contains environment-specific settings for local development

apiVersion: v1
kind: ConfigMap
metadata:
  name: trendmaster-ai-local-config
  namespace: default
  labels:
    app: trendmaster-ai
    environment: local
    managed-by: trendmaster-ai
data:
  environment: "local"
  deployment_mode: "development"
  
  # Kubernetes Configuration
  kubernetes_context: "minikube"
  kubernetes_namespace: "default"
  
  # Prometheus Configuration
  prometheus_url: "http://localhost:9090"
  use_mock_data: "true"
  
  # Safety Settings
  dry_run: "true"
  preview_only: "true"
  verbose_logging: "true"
  
  # Local Development Features
  apply_to_minikube: "false"
  simulate_eks: "true"
  
  # Rate Limiting Configuration
  min_rate_limit: "100"
  max_rate_limit: "10000"
  safety_margin: "1.3"
  
  # Monitoring
  monitoring_enabled: "false"
  dashboard_enabled: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: trendmaster-ai-local
  namespace: default
  labels:
    app: trendmaster-ai
    environment: local
spec:
  selector:
    app: trendmaster-ai
    environment: local
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendmaster-ai-local
  namespace: default
  labels:
    app: trendmaster-ai
    environment: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trendmaster-ai
      environment: local
  template:
    metadata:
      labels:
        app: trendmaster-ai
        environment: local
    spec:
      containers:
      - name: trendmaster-ai
        image: trendmaster-ai:local
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: ENVIRONMENT
          value: "local"
        - name: DRY_RUN
          value: "true"
        - name: USE_MOCK_DATA
          value: "true"
        - name: LOG_LEVEL
          value: "DEBUG"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        - name: output
          mountPath: /app/output
      volumes:
      - name: config
        configMap:
          name: trendmaster-ai-local-config
      - name: output
        emptyDir: {}
      restartPolicy: Always

---
# Local development ingress (optional)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trendmaster-ai-local
  namespace: default
  labels:
    app: trendmaster-ai
    environment: local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: trendmaster-ai.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: trendmaster-ai-local
            port:
              number: 8080