FROM python:3.9-slim as builder

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    python3-dev \
    libffi-dev \
    libssl-dev \
    make \
    libtool \
    autoconf \
    automake \
    libyaml-dev \
    && apt-get clean

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --no-cache-dir --upgrade pip setuptools wheel

COPY requirements-ratelimit.txt .
RUN pip install --no-cache-dir -r requirements-ratelimit.txt --verbose

FROM python:3.9-slim
COPY --from=builder /opt/venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

COPY ./scripts /app/scripts
COPY ./config/rate_limit_values_config.yaml /app/config/rate_limit_values_config.yaml
WORKDIR /app/scripts

CMD ["python", "rate_limit_values.py"]
