# Required
PROMETHEUS_URL: 'https://trickster.orp2.ott.kaltura.com'
GRAFANA_DASHBOARD_URL: 'https://grafana.ott.kaltura.com/d'

# Optional
DAYS_TO_INSPECT: 7
DEVIATION_THRESHOLD: 0.5
EXCESS_DEVIATION_THRESHOLD: 1
K8S_SPIKE_THRESHOLD: 0.1
CSV_OUTPUT: False
IMG_OUTPUT: True
DOCKER: False

# To enable GPT analysis
GPT_ON: False
OPENAI_API_KEY: 'XXXXXXX'

# Required
QUERIES:
  'Nginx Requests Per Minute - 2xx/3xx': 'sum by (path, partner) (increase(service_nginx_request_time_s_count{path!="", partner!=""}[1m]))'
  'Kubernetes Running Pods - Phoenix': 'sum by (phase, kubernetes_node, pod) (increase(kube_pod_status_phase{phase="Running", kubernetes_node!="", pod=~"kphoenix.*"}[1m]))'