apiVersion: v1
data:
  config.yaml: |
    domain: global-ratelimit
    descriptors:
      - key: PARTNER
        value: 313
        descriptors:
        - key: PATH
          value: /api_v3/service/configurations/action/servebydevice
          rate_limit:
            unit: minute
            requests_per_unit: 5000
        - key: PATH
          value: /api_v3/service/asset/action/getplaybackcontext
          rate_limit:
            unit: minute
            requests_per_unit: 30000
        - key: PATH
          value: /api_v3/service/userassetrule/action/list
          rate_limit:
            unit: minute
            requests_per_unit: 58000
        - key: PATH
          value: /api_v3/service/licensedurl/action/get
          rate_limit:
            unit: minute
            requests_per_unit: 58000
        - key: PATH
          value: /api_v3/service/assethistory/action/list
          rate_limit:
            unit: minute
            requests_per_unit: 35000
      - key: PARTNER
        value: 439
        descriptors:
        - key: PATH
          value: /api_v3/service/multirequest
          rate_limit:
            unit: minute
            requests_per_unit: 12000
        - key: PATH
          value: /api_v3/service/userassetrule/action/list
          rate_limit:
            unit: minute
            requests_per_unit: 58000
        - key: PATH
          value: /api_v3/service/asset/action/list
          rate_limit:
            unit: minute
            requests_per_unit: 70000
        - key: PATH
          value: /api_v3/service/assethistory/action/list
          rate_limit:
            unit: minute
            requests_per_unit: 35000
      - key: PARTNER
        value: 3079
        descriptors:
        - key: PATH
          value: /api_v3/service/ottuser/action/get
          rate_limit:
            unit: minute
            requests_per_unit: 35000
        - key: PATH
          value: /api_v3/service/householdquota/action/get
          rate_limit:
            unit: minute
            requests_per_unit: 35000
        - key: PATH
          value: /api_v3/service/asset/action/list
          rate_limit:
            unit: minute
            requests_per_unit: 35000
        - key: PATH
          value: /api_v3/service/configurations/action/servebydevice
          rate_limit:
            unit: minute
            requests_per_unit: 500
      - key: PARTNER
        value: 9020
        descriptors:
        - key: PATH
          value: /api_v3/service/assethistory/action/list
          rate_limit:
            unit: minute
            requests_per_unit: 35000
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","data":{"config.yaml":"domain:
      global-ratelimit\ndescriptors:\n  - key: PARTNER\n    value: 313\n   
      descriptors:\n    - key: PATH\n      value:
      /api_v3/service/configurations/action/servebydevice\n     
      rate_limit:\n        unit: minute\n        requests_per_unit: 5000\n    -
      key: PATH\n      value:
      /api_v3/service/asset/action/getplaybackcontext\n     
      rate_limit:\n        unit: minute\n        requests_per_unit: 30000\n    -
      key: PATH\n      value: /api_v3/service/userassetrule/action/list\n     
      rate_limit:\n        unit: minute\n        requests_per_unit: 58000\n    -
      key: PATH\n      value: /api_v3/service/licensedurl/action/get\n     
      rate_limit:\n        unit: minute\n        requests_per_unit: 58000\n    -
      key: PATH\n      value: /api_v3/service/assethistory/action/list\n     
      rate_limit:\n        unit: minute\n        requests_per_unit: 35000\n  -
      key: PARTNER\n    value: 439\n    descriptors:\n    - key: PATH\n     
      value: /api_v3/service/multirequest\n      rate_limit:\n        unit:
      minute\n        requests_per_unit: 12000\n    - key: PATH\n      value:
      /api_v3/service/userassetrule/action/list\n      rate_limit:\n       
      unit: minute\n        requests_per_unit: 58000\n    - key: PATH\n     
      value: /api_v3/service/asset/action/list\n      rate_limit:\n        unit:
      minute\n        requests_per_unit: 70000\n    - key: PATH\n      value:
      /api_v3/service/assethistory/action/list\n      rate_limit:\n        unit:
      minute\n        requests_per_unit: 35000\n  - key: PARTNER\n    value:
      3079\n    descriptors:\n    - key: PATH\n      value:
      /api_v3/service/ottuser/action/get\n      rate_limit:\n        unit:
      minute\n        requests_per_unit: 35000\n    - key: PATH\n      value:
      /api_v3/service/householdquota/action/get\n      rate_limit:\n       
      unit: minute\n        requests_per_unit: 35000\n    - key: PATH\n     
      value: /api_v3/service/asset/action/list\n      rate_limit:\n        unit:
      minute\n        requests_per_unit: 35000\n    - key: PATH\n      value:
      /api_v3/service/configurations/action/servebydevice\n     
      rate_limit:\n        unit: minute\n        requests_per_unit: 500\n  -
      key: PARTNER\n    value: 9020\n    descriptors:\n    - key: PATH\n     
      value: /api_v3/service/assethistory/action/list\n     
      rate_limit:\n        unit: minute\n        requests_per_unit:
      35000\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"orp2-istio-ratelimit"},"name":"ratelimit-config","namespace":"istio-system"}}
  creationTimestamp: '2022-12-19T08:25:57Z'
  labels:
    app.kubernetes.io/instance: orp2-istio-ratelimit
  name: ratelimit-config
  namespace: istio-system
  resourceVersion: '2074674283'
  uid: 548aa88a-45b1-45f2-9269-566f85b3fd1c
