title: TrendMaster-AI Documentation
description: Intelligent, ML-powered adaptive rate limiting system for Istio service mesh
theme: just-the-docs
url: https://your-org.github.io
baseurl: /TrendMaster-AI

# Enable GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Just the Docs theme configuration
color_scheme: light
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation structure
nav_sort: case_insensitive

# Footer content
footer_content: "Copyright &copy; 2025 TrendMaster-AI Team. Made with ❤️ for the community."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# GitHub repository information
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/your-org/TrendMaster-AI"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

# Callouts
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Aux links for the upper right navigation
aux_links:
  "TrendMaster-AI on GitHub":
    - "https://github.com/your-org/TrendMaster-AI"
  "View CI/CD Status":
    - "https://github.com/your-org/TrendMaster-AI/actions"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Heading anchor links appear on hover over h1-h6 tags in page content
heading_anchors: true

# External navigation links
nav_external_links:
  - title: Docker Hub
    url: https://hub.docker.com/r/trendmaster-ai/adaptive-rate-limiter
  - title: Prometheus
    url: https://prometheus.io/
  - title: Istio
    url: https://istio.io/

# Enable copy code button
enable_copy_code_button: true

# Mermaid diagrams
mermaid:
  version: "9.4.0"